# Generated by Django 4.2.21 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount received (R)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='authorization_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Auth. number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD-10 code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='procedure_codes',
            field=models.TextField(blank=True, help_text='One per line, e.g. 0190 — Consultation', null=True, verbose_name='Procedure codes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='procedure_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Procedure code'),
        ),
    ]
