# Generated by Django 4.2.21 on 2026-05-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_amount_paid_invoice_authorization_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('EFT', 'EFT / Bank Transfer'), ('Medical Aid', 'Medical Aid')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference / EFT ref')),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('scheme_name', models.CharField(max_length=100)),
                ('submission_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Submission / batch reference')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Resubmitted', 'Resubmitted'), ('Paid', 'Paid')], default='Submitted', max_length=20)),
                ('rejection_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rejection code')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('resubmission_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_submissions', to='billing.invoice')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='billing.claimsubmission', verbose_name='Resubmission of')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
