# Generated by Django 4.2.21 on 2026-05-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_consultation_icd10_invoiceitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='diag_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diagnosis code'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NAPPI description'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='procedure_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tariff code'),
        ),
    ]
