# Generated by Django 4.2.21 on 2026-07-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_diagcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Tariff code')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Medical', 'Medical'), ('Surgical', 'Surgical')], default='Medical', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Surgical', 'Surgical')], default='Medical', max_length=10, verbose_name='Medical / Surgical'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='billing.tariffcode'),
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate (R)')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='billing.tariffcode')),
            ],
            options={
                'ordering': ['tariff__code', '-effective_from'],
                'unique_together': {('tariff', 'effective_from')},
            },
        ),
    ]
