
# User already has these codes
existing = {
    '0300','0301','0302','0303','0400','0401','0402',
    '0500','0501','0502','0503','0504','0505','0510','0512','0515',
    '0550','0551','0552','0553','0560','0561','0562','0563','0564','0565','0566','0567','0568',
    '0570','0700','0701','0702','1211'
}

# All codes found in research from GEMS 2016/2017, GEMS 2020, NHRPL 2006 PDFs
found = {
    # 0300 range - soft tissue / minor surgery / wounds
    '0304': ('Major debridement of wound, sloughectomy or secondary suture', 'Minor Surgery / Wound Care'),
    '0305': ('Needle biopsy - soft tissue', 'Minor Surgery / Biopsy'),
    '0306': ('Excision subcutaneous mass less than 2cm: Head and neck (lipoma, cyst)', 'Minor Surgery'),
    '0307': ('Excision and repair by direct suture; excision nail fold or other minor procedures of similar magnitude', 'Minor Surgery'),
    '0308': ('Each additional small procedure done at the same time', 'Minor Surgery'),
    '0309': ('Excision subcutaneous mass greater than 2cm: Head and neck (lipoma, cyst)', 'Minor Surgery'),
    '0310': ('Radical excision of nailbed', 'Minor Surgery'),
    '0311': ('Excision of large benign tumour (more than 5 cm)', 'Minor Surgery'),
    '0313': ('Extensive resection for malignant soft tissue tumour including muscle', 'Minor Surgery / Oncology'),
    '0314': ('Requiring repair by large skin graft or large local flap or other procedures of similar magnitude', 'Minor Surgery / Plastic Surgery'),
    '0315': ('Requiring repair by small skin graft or small local flap or other procedures of similar magnitude', 'Minor Surgery / Plastic Surgery'),
    '0316': ('Fine needle aspiration for soft tissue (all areas)', 'Minor Surgery / Biopsy'),
    '0317': ('Aspiration of cyst or tumour', 'Minor Surgery / Biopsy'),
    '0319': ('Mastotomy with exploration, drainage of abscess or removal of mammary implant', 'Minor Surgery / Breast'),
    '0321': ('Biopsy or excision of cyst, benign tumour, aberrant breast tissue, duct papilloma', 'Minor Surgery / Breast'),
    '0323': ('Subareolar cone excision of ducts or wedge excision of breast', 'Surgery / Breast'),
    '0324': ('Wedge excision of breast and axillary dissection', 'Surgery / Breast'),
    '0325': ('Total mastectomy', 'Surgery / Breast'),
    '0327': ('Total mastectomy with axillary gland biopsy', 'Surgery / Breast'),
    '0329': ('Total mastectomy with axillary gland dissection', 'Surgery / Breast'),
    '0330': ('Nipple and areola reconstruction', 'Surgery / Breast Reconstruction'),
    '0331': ('Subcutaneous mastectomy for disease of breast including reconstruction: Unilateral', 'Surgery / Breast'),
    '0333': ('Subcutaneous mastectomy for disease of breast including reconstruction: Bilateral', 'Surgery / Breast'),
    '0334': ('Removal of breast implant by means of capsulectomy: Per breast', 'Surgery / Breast'),
    '0335': ('Implantation of internal subpectoral mammary prosthesis in post mastectomy patients', 'Surgery / Breast Reconstruction'),
    '0337': ('Reduction: Mammoplasty for pathological hypertrophy - unilateral', 'Surgery / Breast'),
    '0339': ('Reduction: Mammoplasty for pathological hypertrophy - bilateral', 'Surgery / Breast'),
    '0341': ('Gynaecomastia: Unilateral', 'Surgery / Breast'),
    '0343': ('Gynaecomastia: Bilateral', 'Surgery / Breast'),
    '0351': ('Major Burns: Resuscitation including supervision and intravenous therapy - first 48 hours', 'Emergency / Burns'),
    '0353': ('Tangential excision and grafting: Small', 'Surgery / Burns'),
    '0354': ('Tangential excision and grafting: Large', 'Surgery / Burns'),
    '0355': ('Skin flap in acute hand injuries where flap is taken from a site remote from the injured finger', 'Surgery / Plastic'),
    '0357': ('Small skin graft in acute hand injury', 'Surgery / Plastic'),
    '0359': ('Release of extensive skin contracture and/or excision of scar tissue with major skin graft resurfacing', 'Surgery / Plastic'),
    '0361': ('Z-plasty', 'Surgery / Plastic'),
    '0363': ('Local flap and skin graft', 'Surgery / Plastic'),
    '0365': ('Cross finger flap (all stages)', 'Surgery / Plastic'),
    '0367': ('Palmar flap (all stages)', 'Surgery / Plastic'),
    '0369': ('Distant flap: First stage', 'Surgery / Plastic'),
    '0371': ('Distant flap: Subsequent stage', 'Surgery / Plastic'),
    '0373': ('Transfer neurovascular island flap', 'Surgery / Plastic'),
    '0374': ('Syndactyly: Separation of, including skin graft for one web (with skin flap and graft)', 'Surgery / Plastic'),
    '0375': ('Dupuytren contracture: Fasciotomy', 'Surgery / Orthopaedic'),
    '0376': ('Dupuytren contracture: Fasciectomy', 'Surgery / Orthopaedic'),
    '0377': ('Standard acupuncture', 'Acupuncture'),
    '0378': ('Laser acupuncture using more than six points', 'Acupuncture'),
    '0379': ('Electro-acupuncture', 'Acupuncture'),
    '0380': ('Scalp acupuncture', 'Acupuncture'),
    '0381': ('Micro-acupuncture (ear, hand)', 'Acupuncture'),
    '0383': ('Fracture (reduction under general anaesthetic): Scapula', 'Orthopaedics / Fracture'),
    '0384': ('Fracture: Scapula - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0386': ('Fracture: Clavicle - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0387': ('Fracture (reduction under general anaesthetic): Clavicle', 'Orthopaedics / Fracture'),
    '0388': ('Percutaneous pinning of supracondylar fracture: Elbow - stand-alone procedure', 'Orthopaedics / Fracture'),
    '0389': ('Fracture (reduction under general anaesthetic): Humerus', 'Orthopaedics / Fracture'),
    '0390': ('Fracture: Humerus - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0391': ('Fracture (reduction under general anaesthetic): Radius and/or ulna', 'Orthopaedics / Fracture'),
    '0392': ('Fracture (reduction under general anaesthetic): Open reduction of both radius and ulna', 'Orthopaedics / Fracture'),
    # 0400 range - fractures lower limb and hand
    '0403': ('Fracture (reduction under general anaesthetic): Bennett fracture-dislocation', 'Orthopaedics / Fracture'),
    '0404': ('Fracture: Bennett fracture/dislocation - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0405': ('Fracture (reduction under general anaesthetic): Open treatment of metacarpal - simple', 'Orthopaedics / Fracture'),
    '0406': ('Fracture: Metacarpal bone - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0409': ('Fracture (reduction under general anaesthetic): Finger phalanx - distal, simple', 'Orthopaedics / Fracture'),
    '0410': ('Fracture: Finger phalanx, distal, simple - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0411': ('Fracture (reduction under general anaesthetic): Finger phalanx - distal, compound', 'Orthopaedics / Fracture'),
    '0413': ('Fracture (reduction under general anaesthetic): Proximal or middle - simple', 'Orthopaedics / Fracture'),
    '0414': ('Fracture: Finger phalanx, proximal or middle - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0415': ('Fracture (reduction under general anaesthetic): Proximal or middle - compound', 'Orthopaedics / Fracture'),
    '0417': ('Fracture (reduction under general anaesthetic): Pelvis fracture - closed', 'Orthopaedics / Fracture'),
    '0419': ('Fracture (reduction under general anaesthetic): Pelvis - operative reduction and fixation', 'Orthopaedics / Fracture'),
    '0420': ('Fracture: Acetabulum - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0421': ('Fracture (reduction under general anaesthetic): Femur - neck or shaft', 'Orthopaedics / Fracture'),
    '0422': ('Fracture: Femur neck or shaft - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0425': ('Fracture (reduction under general anaesthetic): Patella', 'Orthopaedics / Fracture'),
    '0426': ('Fracture: Patella - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0429': ('Fracture (reduction under general anaesthetic): Tibia with or without fibula', 'Orthopaedics / Fracture'),
    '0430': ('Fracture: Tibia, with or without fibula - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0433': ('Fracture (reduction under general anaesthetic): Fibula shaft', 'Orthopaedics / Fracture'),
    '0434': ('Fracture: Fibula shaft - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0435': ('Fracture (reduction under general anaesthetic): Malleolus of ankle', 'Orthopaedics / Fracture'),
    '0436': ('Fracture: Ankle malleolus - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0437': ('Fracture (reduction under general anaesthetic): Fracture-dislocation of ankle', 'Orthopaedics / Fracture'),
    '0438': ('Fracture (reduction under general anaesthetic): Open reduction talus fracture', 'Orthopaedics / Fracture'),
    '0439': ('Fracture (reduction under general anaesthetic): Tarsal bones (excluding talus and calcaneus)', 'Orthopaedics / Fracture'),
    '0440': ('Fracture (reduction under general anaesthetic): Open reduction calcaneus fracture', 'Orthopaedics / Fracture'),
    '0441': ('Fracture (reduction under general anaesthetic): Metatarsal', 'Orthopaedics / Fracture'),
    '0442': ('Fracture: Metatarsal bones - open reduction with internal fixation', 'Orthopaedics / Fracture'),
    '0443': ('Fracture (reduction under general anaesthetic): Toe phalanx - distal, simple', 'Orthopaedics / Fracture'),
    '0444': ('Fracture: Toe phalanx, distal - open reduction with internal fixation', 'Orthopaedics / Fracture'),
    '0445': ('Fracture (reduction under general anaesthetic): Toe phalanx - compound', 'Orthopaedics / Fracture'),
    '0446': ('Fracture: Tarsal bones (excl. talus and calcaneus) - open reduction with internal fixation', 'Orthopaedics / Fracture'),
    '0447': ('Fracture (reduction under general anaesthetic): Other - simple', 'Orthopaedics / Fracture'),
    '0448': ('Fracture: Calcaneus (reduction under general anaesthetic)', 'Orthopaedics / Fracture'),
    '0449': ('Fracture (reduction under general anaesthetic): Other - compound', 'Orthopaedics / Fracture'),
    '0451': ('Fracture (reduction under general anaesthetic): Sternum and/or ribs - closed', 'Orthopaedics / Fracture'),
    '0452': ('Fracture (reduction under general anaesthetic): Sternum and/or ribs open reduction and fixation of multiple fractured ribs', 'Orthopaedics / Fracture'),
    '0455': ('Fracture (reduction under general anaesthetic): Spine with or without paralysis - cervical', 'Orthopaedics / Fracture'),
    '0456': ('Fracture (reduction under general anaesthetic): Spine with or without paralysis - rest', 'Orthopaedics / Fracture'),
    '0461': ('Fracture (reduction under general anaesthetic): Compression fracture - cervical', 'Orthopaedics / Fracture'),
    '0462': ('Fracture (reduction under general anaesthetic): Compression fracture - rest', 'Orthopaedics / Fracture'),
    '0463': ('Fracture (reduction under general anaesthetic): Spinous or transverse processes - cervical', 'Orthopaedics / Fracture'),
    '0464': ('Fracture (reduction under general anaesthetic): Spinous or transverse processes - rest', 'Orthopaedics / Fracture'),
    '0465': ('Fractures involving large joints (includes the item for the relative bone)', 'Orthopaedics / Fracture'),
    '0466': ('Fractures involving digital joints - open reduction and internal fixation', 'Orthopaedics / Fracture'),
    '0473': ('Percutaneous insertion plus subsequent removal of Kirschner wires or Steinmann pins', 'Orthopaedics / Fixation'),
    '0475': ('Bonegrafting or internal fixation for malunion or non-union: Femur, tibia, humerus, radius and ulna', 'Orthopaedics / Bone Surgery'),
    '0479': ('Bonegrafting or internal fixation for malunion or non-union: Other bones', 'Orthopaedics / Bone Surgery'),
    '0480': ('Radical resection of bone tumour/infection: Ilium incl. acetabulum, both pubic rami, or ischium and acetabulum', 'Orthopaedics / Bone Tumour'),
    '0481': ('Radical resection of bone tumour: Fibula', 'Orthopaedics / Bone Tumour'),
    '0482': ('Radical resection of bone tumour: Femur or knee', 'Orthopaedics / Bone Tumour'),
    '0483': ('Radical resection of malignant bone tumour: Scapula', 'Orthopaedics / Bone Tumour'),
    '0484': ('Radical resection of bone tumour: Clavicle', 'Orthopaedics / Bone Tumour'),
    '0485': ('Radical resection of bone tumour: Metatarsal', 'Orthopaedics / Bone Tumour'),
    '0497': ('Resection of bone or tumour with or without grafting (benign)', 'Orthopaedics / Bone Surgery'),
    '0498': ('Resection of bone or tumour with or without grafting (malignant) - does not include digits', 'Orthopaedics / Bone Surgery'),
    '0499': ('Grafts to cysts: Large bones', 'Orthopaedics / Bone Graft'),
    # 0500 range
    '0506': ('Harvesting of graft: Cartilage graft, costochondral', 'Orthopaedics / Bone Graft'),
    '0507': ('Removal of autogenous bone for grafting', 'Orthopaedics / Bone Graft'),
    '0509': ('Acute or chronic osteomyelitis: Conservative treatment', 'Orthopaedics / Infection'),
    '0511': ('Acute or chronic osteomyelitis: Operation (tariff applicable for compound fracture of bone involved)', 'Orthopaedics / Infection'),
    '0513': ('Osteotomy: Single metatarsal', 'Orthopaedics / Osteotomy'),
    '0516': ('Osteotomy: Pelvic', 'Orthopaedics / Osteotomy'),
    '0521': ('Osteotomy: Femoral: Proximal', 'Orthopaedics / Osteotomy'),
    '0527': ('Osteotomy: Knee region', 'Orthopaedics / Osteotomy'),
    '0528': ('Osteotomy: Os Calcis (Dwyer operation)', 'Orthopaedics / Osteotomy'),
    '0530': ('Osteotomy: Metacarpal and phalanx - corrective for malunion or rotation', 'Orthopaedics / Osteotomy'),
    '0531': ('Rotational osteotomy of tibia and fibula - stand-alone procedure', 'Orthopaedics / Osteotomy'),
    '0532': ('Osteotomy: Rotation osteotomy of the radius, ulna or humerus', 'Orthopaedics / Osteotomy'),
    '0533': ('Osteotomy: Single metatarsal', 'Orthopaedics / Osteotomy'),
    '0534': ('Osteotomy: Multiple metatarsal osteotomies', 'Orthopaedics / Osteotomy'),
    '0535': ('Exostosis: Excision - readily accessible sites', 'Orthopaedics / Bone Surgery'),
    '0537': ('Exostosis: Excision - less accessible sites', 'Orthopaedics / Bone Surgery'),
    '0539': ('Needle biopsy: Spine (no after-care)', 'Orthopaedics / Biopsy'),
    '0541': ('Needle biopsy: Other sites (no after-care)', 'Orthopaedics / Biopsy'),
    '0543': ('Biopsy: Open - readily accessible site', 'Orthopaedics / Biopsy'),
    '0545': ('Biopsy: Open - less accessible site', 'Orthopaedics / Biopsy'),
    '0547': ('Joint: Dislocation - clavicle either end', 'Orthopaedics / Dislocation'),
    '0549': ('Joint: Dislocation - shoulder', 'Orthopaedics / Dislocation'),
    '0555': ('Joint: Dislocation - lunate', 'Orthopaedics / Dislocation'),
    '0556': ('Joint: Dislocation - carpo-metacarpo dislocation', 'Orthopaedics / Dislocation'),
    '0557': ('Joint: Dislocation - metacarpo-phalangeal or interphalangeal (hand)', 'Orthopaedics / Dislocation'),
    '0559': ('Joint: Dislocation - hip', 'Orthopaedics / Dislocation'),
    '0569': ('Joint: Dislocation - intertarsal or tarsometatarsal or mid-tarsal', 'Orthopaedics / Dislocation'),
    '0571': ('Joint: Dislocation - meta-tarsophalangeal or interphalangeal joints (foot)', 'Orthopaedics / Dislocation'),
    '0573': ('Joint: Dislocation - spine with or without paralysis', 'Orthopaedics / Dislocation'),
    '0578': ('Operations for dislocations: Recurrent dislocation of shoulder', 'Orthopaedics / Dislocation'),
    '0579': ('Operations for dislocations: Recurrent dislocation of all other joints', 'Orthopaedics / Dislocation'),
    '0582': ('Capsulotomy or arthrotomy or biopsy or drainage of joint: Small joint (including three weeks after-care)', 'Orthopaedics / Joint Surgery'),
    '0583': ('Capsulotomy or arthrotomy or biopsy or drainage of joint: Large joint (including three weeks after-care)', 'Orthopaedics / Joint Surgery'),
    '0585': ('Capsulectomy digital joint', 'Orthopaedics / Joint Surgery'),
    '0586': ('Multiple percutaneous capsulotomies of metacarpophalangeal joints', 'Orthopaedics / Joint Surgery'),
    '0587': ('Release of digital joint contracture', 'Orthopaedics / Joint Surgery'),
    '0589': ('Synovectomy: Digital joint', 'Orthopaedics / Joint Surgery'),
    '0592': ('Synovectomy: Large joint', 'Orthopaedics / Joint Surgery'),
    '0593': ('Tendon synovectomy', 'Orthopaedics / Tendon Surgery'),
    '0597': ('Arthrodesis: Shoulder', 'Orthopaedics / Arthrodesis'),
    '0598': ('Arthrodesis: Elbow', 'Orthopaedics / Arthrodesis'),
    '0599': ('Arthrodesis: Wrist', 'Orthopaedics / Arthrodesis'),
    '0600': ('Arthrodesis: Digital joint', 'Orthopaedics / Arthrodesis'),
    '0601': ('Arthrodesis: Hip', 'Orthopaedics / Arthrodesis'),
    '0602': ('Arthrodesis: Knee', 'Orthopaedics / Arthrodesis'),
    '0603': ('Arthrodesis: Ankle', 'Orthopaedics / Arthrodesis'),
    '0604': ('Arthrodesis: Sub-talar', 'Orthopaedics / Arthrodesis'),
    '0605': ('Arthrodesis: Stabilisation of foot (triple-arthrodesis)', 'Orthopaedics / Arthrodesis'),
    '0607': ('Arthrodesis: Mid-tarsal wedge resection', 'Orthopaedics / Arthrodesis'),
    '0614': ('Arthroplasty: Debridement large joints', 'Orthopaedics / Arthroplasty'),
    '0615': ('Arthroplasty: Excision medial or lateral end of clavicle', 'Orthopaedics / Arthroplasty'),
    '0617': ('Shoulder: Acromioplasty', 'Orthopaedics / Arthroplasty'),
    '0619': ('Shoulder: Partial replacement', 'Orthopaedics / Arthroplasty'),
    '0620': ('Shoulder: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0621': ('Elbow: Excision head of radius', 'Orthopaedics / Arthroplasty'),
    '0622': ('Elbow: Excision', 'Orthopaedics / Arthroplasty'),
    '0623': ('Elbow: Partial replacement', 'Orthopaedics / Arthroplasty'),
    '0624': ('Elbow: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0625': ('Wrist: Excision distal end of ulna', 'Orthopaedics / Arthroplasty'),
    '0626': ('Wrist: Excision single bone', 'Orthopaedics / Arthroplasty'),
    '0627': ('Wrist: Excision proximal row', 'Orthopaedics / Arthroplasty'),
    '0631': ('Wrist: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0635': ('Digital Joint: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0637': ('Hip: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0641': ('Hip: Prosthetic replacement of femoral head', 'Orthopaedics / Arthroplasty'),
    '0643': ('Hip: Girdlestone', 'Orthopaedics / Arthroplasty'),
    '0645': ('Knee: Partial replacement', 'Orthopaedics / Arthroplasty'),
    '0646': ('Knee: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0649': ('Ankle: Total replacement', 'Orthopaedics / Arthroplasty'),
    '0650': ('Ankle: Astragalectomy', 'Orthopaedics / Arthroplasty'),
    '0661': ('Aspiration of joint or intra-articular injection (not including after-care)', 'Injections / Intra-articular'),
    '0663': ('Multiple intra-articular injections for rheumatoid arthritis: First session', 'Injections / Intra-articular'),
    '0665': ('Multiple intra-articular injections for rheumatoid arthritis: Subsequent sessions', 'Injections / Intra-articular'),
    '0667': ('Arthroscopy (excluding after-care)', 'Orthopaedics / Arthroscopy'),
    '0669': ('Manipulating knee or shoulder joint under general anaesthetic', 'Orthopaedics / Joint'),
    '0673': ('Meniscectomy or operation for other internal derangement of knee', 'Orthopaedics / Knee'),
    '0675': ('Joint ligament reconstruction or suture: Ankle - collateral', 'Orthopaedics / Ligament'),
    '0676': ('Joint ligament reconstruction or suture: Ankle (Watson-Jones type)', 'Orthopaedics / Ligament'),
    '0677': ('Joint ligament reconstruction or suture: Knee - collateral', 'Orthopaedics / Ligament'),
    '0678': ('Joint ligament reconstruction or suture: Knee - cruciate', 'Orthopaedics / Ligament'),
    '0679': ('Joint ligament reconstruction or suture: Ligament augmentation procedure of knee', 'Orthopaedics / Ligament'),
    '0680': ('Joint ligament reconstruction or suture: Digital joint ligament', 'Orthopaedics / Ligament'),
    '0681': ('Amputation humerus: Includes primary closure', 'Surgery / Amputation'),
    '0682': ('Amputation: Fore-quarter amputation', 'Surgery / Amputation'),
    '0683': ('Amputation: Through shoulder', 'Surgery / Amputation'),
    '0684': ('Amputation: Forearm', 'Surgery / Amputation'),
    '0685': ('Amputation: Upper arm or forearm', 'Surgery / Amputation'),
    '0686': ('Amputation: Ankle (Syme, Pirogoff type)', 'Surgery / Amputation'),
    '0687': ('Partial amputation of the hand: One ray', 'Surgery / Amputation'),
    '0688': ('Amputation: Foot, midtarsal (Chopart type)', 'Surgery / Amputation'),
    '0691': ('Amputation: Whole or part of finger', 'Surgery / Amputation'),
    '0692': ('Scar revision/secondary closure: Amputated thigh, through femur, any level', 'Surgery / Amputation'),
    '0693': ('Hindquarter amputation', 'Surgery / Amputation'),
    '0694': ('Scar revision/secondary closure: Amputated leg, through tibia and fibula, any level', 'Surgery / Amputation'),
    '0695': ('Amputation: Through hip joint region', 'Surgery / Amputation'),
    '0696': ('Re-amputation: Thigh, through femur, any level', 'Surgery / Amputation'),
    '0697': ('Amputation: Through thigh', 'Surgery / Amputation'),
    '0698': ('Re-amputation: Leg, through tibia and fibula', 'Surgery / Amputation'),
    '0699': ('Amputation: Below knee, through knee or Syme', 'Surgery / Amputation'),
    '0703': ('Amputation: Foot - one ray', 'Surgery / Amputation'),
    '0704': ('Scar revision/secondary closure: Amputated forearm', 'Surgery / Amputation'),
    '0705': ('Amputation: Toe', 'Surgery / Amputation'),
    '0706': ('Post-amputation reconstruction: Skin flap taken from site remote from injured finger', 'Surgery / Reconstruction'),
    '0707': ('Post-amputation reconstruction: Krukenberg reconstruction', 'Surgery / Reconstruction'),
    '0708': ('Re-amputation: Humerus', 'Surgery / Amputation'),
    '0710': ('Re-amputation: Through forearm', 'Surgery / Amputation'),
    '0711': ('Post-amputation reconstruction: Pollicisation of the finger (to include all stages)', 'Surgery / Reconstruction'),
    '0712': ('Post-amputation reconstruction: Toe to thumb transfer', 'Surgery / Reconstruction'),
    '0713': ('Electromyography', 'Neurology / Electrodiagnostics'),
    '0714': ('Electro-myographic neuromuscular junctional study, including edrophonium response', 'Neurology / Electrodiagnostics'),
    '0715': ('Strength duration curve per session', 'Neurology / Electrodiagnostics'),
    '0717': ('Electrical examination of single nerve or muscle', 'Neurology / Electrodiagnostics'),
    '0718': ('Oxidative study for mitochondrial function', 'Neurology / Electrodiagnostics'),
    '0721': ('Voltage integration during isometric contraction', 'Neurology / Electrodiagnostics'),
    '0723': ('Tonometry with edrophonium', 'Neurology / Electrodiagnostics'),
    '0725': ('Isometric tension studies with edrophonium', 'Neurology / Electrodiagnostics'),
    '0727': ('Cranial reflex study (both early and late responses) - unilateral', 'Neurology / Electrodiagnostics'),
    '0728': ('Cranial reflex study (both early and late responses) - bilateral', 'Neurology / Electrodiagnostics'),
    '0729': ('Tendon reflex time', 'Neurology / Electrodiagnostics'),
    '0730': ('Limb brain somatosensory studies (per limb)', 'Neurology / Electrodiagnostics'),
    '0731': ('Vision and audio-sensory studies', 'Neurology / Electrodiagnostics'),
    '0733': ('Motor nerve conduction studies (single nerve)', 'Neurology / Electrodiagnostics'),
    '0735': ('Examinations of sensory nerve conduction by sweep averages (single nerve)', 'Neurology / Electrodiagnostics'),
    '0737': ('Biopsy for motor nerve terminals and end plates', 'Neurology / Biopsy'),
    '0739': ('Combined muscle biopsy with end plates and nerve terminal biopsy', 'Neurology / Biopsy'),
    '0740': ('Muscle fatigue studies', 'Neurology / Electrodiagnostics'),
    '0741': ('Muscle biopsy', 'Neurology / Biopsy'),
    '0742': ('Global fee for all muscle studies, including histochemical studies', 'Neurology / Electrodiagnostics'),
    '0743': ('Major compartmental decompression', 'Surgery / Decompression'),
    '0744': ('Decompression operation: Fasciotomy only', 'Surgery / Decompression'),
    '0745': ('Muscle and tendon repair: Biceps humeri', 'Surgery / Tendon'),
    '0746': ('Muscle and tendon repair: Removal of calcification in rotator cuff', 'Surgery / Tendon'),
    '0747': ('Muscle and tendon repair: Rotator cuff', 'Surgery / Tendon'),
    '0748': ('Muscle and tendon repair: Debridement rotator cuff', 'Surgery / Tendon'),
    '0749': ('Muscle and tendon repair: Scapulopexy - stand-alone procedure', 'Surgery / Tendon'),
    '0755': ('Muscle and tendon repair: Infrapatellar of quadriceps tendon', 'Surgery / Tendon'),
    '0757': ('Muscle and tendon repair: Achilles tendon repair', 'Surgery / Tendon'),
    '0759': ('Muscle and tendon repair: Other single tendon', 'Surgery / Tendon'),
    '0760': ('Hand: Flexor tendon suture - primary, zone 1 (each)', 'Surgery / Hand Tendon'),
    '0761': ('Hand: Flexor tendon repair - primary, zone 2 (no mans land), each', 'Surgery / Hand Tendon'),
    '0762': ('Hand: Flexor tendon suture - primary, zone 3 and 4 (wrist and forearm), each', 'Surgery / Hand Tendon'),
    '0763': ('Muscle and tendon repair: Tendon or ligament injection', 'Injections / Tendon'),
    '0764': ('Hand: Flexor tendon repair - secondary, zone 1', 'Surgery / Hand Tendon'),
    '0765': ('Hand: Flexor tendon repair - secondary, zone 2 (no mans land)', 'Surgery / Hand Tendon'),
    '0766': ('Hand: Flexor tendon repair - secondary, zone 3 and 4 (wrist and forearm)', 'Surgery / Hand Tendon'),
    '0767': ('Hand: Flexor tendon suture - primary (per tendon)', 'Surgery / Hand Tendon'),
    '0768': ('Repair: Intrinsic muscles of hand (each)', 'Surgery / Hand Tendon'),
    '0769': ('Hand: Flexor tendon suture: Secondary (per tendon)', 'Surgery / Hand Tendon'),
    '0771': ('Extensor tendon suture: Primary (per tendon)', 'Surgery / Hand Tendon'),
    '0773': ('Extensor tendon suture: Secondary (per tendon)', 'Surgery / Hand Tendon'),
    '0774': ('Repair of Boutonniere deformity or Mallet finger with graft', 'Surgery / Hand Tendon'),
    '0775': ('Free tendon graft', 'Surgery / Tendon Graft'),
    '0776': ('Reconstruction of pulley for flexor tendon', 'Surgery / Hand Tendon'),
    '0777': ('Tendon graft: Finger - flexor', 'Surgery / Tendon Graft'),
    '0779': ('Tendon graft: Finger - extensor', 'Surgery / Tendon Graft'),
    '0780': ('Two stage flexor tendon graft using silastic rod', 'Surgery / Tendon Graft'),
    '0781': ('Tendon freeing operation, except where specified elsewhere', 'Surgery / Tendon'),
    '0782': ('Carpal tunnel syndrome', 'Surgery / Hand'),
    '0783': ('Tenolysis: De Quervain', 'Surgery / Hand Tendon'),
    '0784': ('Trigger finger', 'Surgery / Hand Tendon'),
    '0785': ('Flexor tendon freeing operation following free tendon graft or suture', 'Surgery / Hand Tendon'),
    '0787': ('Extensor tendon freeing operation following graft or suture in finger, hand or forearm, each tendon', 'Surgery / Hand Tendon'),
    '0788': ('Intrinsic tendon release per finger', 'Surgery / Hand Tendon'),
    '0789': ('Central tendon tenotomy for Boutonniere deformity', 'Surgery / Hand Tendon'),
    '0790': ('Tenodesis: Digital joint', 'Surgery / Hand Tendon'),
    '0791': ('Single tendon transfer', 'Surgery / Tendon Transfer'),
    '0792': ('Multiple tendon transfer', 'Surgery / Tendon Transfer'),
    '0793': ('Hamstring to quadriceps transfer', 'Surgery / Tendon Transfer'),
    '0794': ('Pectoralis major or Latissimus dorsi transfer to biceps tendon', 'Surgery / Tendon Transfer'),
    '0795': ('Tendon transfer at elbow', 'Surgery / Tendon Transfer'),
    # 1200-1299 range
    '1200': ('Carbon monoxide diffusing capacity, any method', 'Pulmonology / Lung Function'),
    '1201': ('Maximum inspiratory/expiratory pressure', 'Pulmonology / Lung Function'),
    '1202': ('Insertion of central venous catheter via peripheral vein in neonates', 'Critical Care / Neonatal'),
    '1204': ('Intensive care: Category 1 (High Care) - cases requiring intensive monitoring', 'Critical Care / ICU'),
    '1205': ('Intensive care: Category 2 (ICU) - cases requiring active system support (first period)', 'Critical Care / ICU'),
    '1206': ('Intensive care: Category 2 (ICU) - cases requiring active system support (second period)', 'Critical Care / ICU'),
    '1207': ('Intensive care: Category 2 (ICU) - cases requiring active system support (subsequent period)', 'Critical Care / ICU'),
    '1208': ('Intensive care: Category 3 (ICU) - cases with multiple organ failure (first period)', 'Critical Care / ICU'),
    '1209': ('Intensive care: Category 3 (ICU) - cases with multiple organ failure (second period)', 'Critical Care / ICU'),
    '1210': ('Intensive care: Category 3 (ICU) - cases with multiple organ failure (subsequent period)', 'Critical Care / ICU'),
    '1212': ('Ventilation: First day', 'Critical Care / Ventilation'),
    '1213': ('Ventilation: Subsequent days, per day', 'Critical Care / Ventilation'),
    '1214': ('Ventilation: After two weeks, per day', 'Critical Care / Ventilation'),
    '1215': ('Insertion of arterial pressure cannula', 'Critical Care / Procedures'),
    '1216': ('Insertion of Swan Ganz catheter for haemodynamics monitoring', 'Critical Care / Procedures'),
    '1217': ('Insertion of central venous line via peripheral vein', 'Critical Care / Procedures'),
    '1218': ('Insertion of central venous line via subclavian or jugular veins', 'Critical Care / Procedures'),
    '1219': ('Hyperalimentation (daily tariff)', 'Critical Care / Nutrition'),
    '1220': ('Patient-controlled analgesic pump: Hire fee per 24 hours', 'Critical Care / Pain Management'),
    '1221': ('Professional fee for managing a patient-controlled analgesic pump: First 24 hours', 'Critical Care / Pain Management'),
    '1222': ('Mediastinal tumours', 'Thoracic Surgery'),
    '1223': ('Mediastinoscopy', 'Thoracic Surgery'),
    '1224': ('Mediastinotomy', 'Thoracic Surgery'),
    '1225': ('Excision of malignant chest wall tumours involving sternum and multiple ribs', 'Thoracic Surgery'),
    '1226': ('Removal of single rib with a lesion', 'Thoracic Surgery'),
    '1227': ('Prolonged neonatal resuscitation', 'Emergency / Neonatal'),
    '1228': ('General Practitioner fee for the taking of an ECG only: Without effort (item 1232)', 'Cardiology / ECG'),
    '1229': ('General Practitioner fee for the taking of an ECG only: Without and with effort (item 1233)', 'Cardiology / ECG'),
    '1230': ('Physician fee for interpreting an ECG: Without effort', 'Cardiology / ECG'),
    '1231': ('Physician fee for interpreting an ECG: With and without effort', 'Cardiology / ECG'),
    '1232': ('Electrocardiogram: Without effort', 'Cardiology / ECG'),
    '1233': ('Electrocardiogram: With and without effort', 'Cardiology / ECG'),
    '1234': ('Effort electrocardiogram with special bicycle ergometer, monitoring apparatus and associated personnel', 'Cardiology / Stress Test'),
    '1235': ('Multi-stage treadmill test', 'Cardiology / Stress Test'),
    '1236': ('Electrocardiogram without effort: Under four years old', 'Cardiology / ECG'),
    '1237': ('24-hour ambulatory blood pressure: Hire fee', 'Cardiology / Ambulatory Monitoring'),
    '1238': ('24-hour ambulatory ECG monitoring (holter): Hire fee', 'Cardiology / Ambulatory Monitoring'),
    '1239': ('24-hour ambulatory ECG monitoring (holter): Interpretation', 'Cardiology / Ambulatory Monitoring'),
    '1240': ('Signal averaged electrocardiogram', 'Cardiology / ECG'),
    '1241': ('X-ray Screening: Chest', 'Radiology / Chest'),
    '1242': ('X-ray screening: Prosthetic valves', 'Radiology / Chest'),
    '1243': ('Two-week event triggered ambulatory ECG monitoring: Hire fee', 'Cardiology / Ambulatory Monitoring'),
    '1244': ('Two-week event triggered ambulatory ECG monitoring: Interpretation', 'Cardiology / Ambulatory Monitoring'),
    '1245': ('Angiography cerebral: First two series', 'Radiology / Angiography'),
    '1246': ('Angiography peripheral: Per limb', 'Radiology / Angiography'),
    '1247': ('Cardioversion for arrhythmias (any method) with doctor in attendance', 'Cardiology / Emergency'),
    '1248': ('Paracentesis of pericardium', 'Cardiology / Procedures'),
    '1249': ('Right and left cardiac catheterisation without coronary angiography (with or without biopsy)', 'Cardiology / Catheterisation'),
    '1250': ('Endomyocardial biopsy', 'Cardiology / Procedures'),
    '1251': ('Transeptal puncture', 'Cardiology / Procedures'),
    '1252': ('Left heart catheterisation with coronary angiography (with or without biopsy)', 'Cardiology / Catheterisation'),
    '1253': ('Right heart catheterisation (with or without biopsy)', 'Cardiology / Catheterisation'),
    '1254': ('Catheterisation of coronary artery bypass grafts and/or internal mammary grafts', 'Cardiology / Catheterisation'),
    '1255': ('Tilt test', 'Cardiology / Diagnostic'),
    '1256': ('Ventricular stimulation study', 'Cardiology / Electrophysiology'),
    '1257': ('Full electrophysiological study', 'Cardiology / Electrophysiology'),
    '1258': ('Pacemaker: Permanent - single chamber', 'Cardiology / Pacemaker'),
    '1259': ('Pacemaker: Permanent - dual chamber', 'Cardiology / Pacemaker'),
    '1260': ('AV nodal ablation', 'Cardiology / Electrophysiology'),
    '1261': ('Accessory pathway ablation', 'Cardiology / Electrophysiology'),
    '1262': ('Electrophysiological mapping', 'Cardiology / Electrophysiology'),
    '1263': ('Insertion transvenous implantable defibrillator', 'Cardiology / Procedures'),
    '1264': ('Test for implantable transvenous defibrillator', 'Cardiology / Procedures'),
    '1265': ('Renewal of pacemaker unit only, team fee', 'Cardiology / Pacemaker'),
    '1266': ('Resiting pacemaker generator', 'Cardiology / Pacemaker'),
    '1267': ('Repositioning of catheter electrode', 'Cardiology / Pacemaker'),
    '1268': ('Threshold testing: Own equipment', 'Cardiology / Pacemaker'),
    '1269': ('Threshold testing: Hospital equipment', 'Cardiology / Pacemaker'),
    '1270': ('Programming of atrio-ventricular sequential pacemaker', 'Cardiology / Pacemaker'),
    '1271': ('Cardiological supervision of Dobutamine magnetic resonance stress testing', 'Cardiology / Stress Test'),
    '1273': ('Insertion of temporary pacemaker', 'Cardiology / Pacemaker'),
    '1274': ('Percutaneous transluminal thrombectomy for clot extraction in native coronary arteries and bypass', 'Cardiology / Intervention'),
    '1275': ('Termination of arrhythmia - programmed stipulation and lead insertion of temporary pacer', 'Cardiology / Electrophysiology'),
    '1276': ('Percutaneous transluminal angioplasty: First cardiologist - single lesion', 'Cardiology / Intervention'),
    '1277': ('Percutaneous transluminal angioplasty: Second cardiologist - single lesion', 'Cardiology / Intervention'),
    '1278': ('Percutaneous transluminal angioplasty: First cardiologist - second lesion', 'Cardiology / Intervention'),
    '1279': ('Percutaneous transluminal angioplasty: Second cardiologist - second lesion', 'Cardiology / Intervention'),
    '1280': ('Percutaneous transluminal angioplasty: First cardiologist - third or subsequent lesions (each)', 'Cardiology / Intervention'),
    '1281': ('Percutaneous transluminal angioplasty: Second cardiologist - third or subsequent lesions (each)', 'Cardiology / Intervention'),
    '1282': ('Use of balloon procedures (atrial septostomy, pulmonary valve valvuloplasty, aortic valve valvuloplasty): First cardiologist', 'Cardiology / Intervention'),
    '1283': ('Use of balloon procedure as in Item 1282: Second cardiologist', 'Cardiology / Intervention'),
    '1284': ('Atherectomy: Single lesion - first cardiologist', 'Cardiology / Intervention'),
    '1285': ('Atherectomy: Single lesion - second cardiologist', 'Cardiology / Intervention'),
    '1286': ('Insertion of intravascular stent: First cardiologist', 'Cardiology / Intervention'),
    '1287': ('Insertion of intravascular stent: Second cardiologist', 'Cardiology / Intervention'),
    '1288': ('Cardiac catheterisation for congenital heart disease: All ages above one year old', 'Cardiology / Congenital'),
    '1289': ('Paediatric cardiac catheterisation: Infants below the age of one year', 'Cardiology / Congenital'),
    '1290': ('Use of balloon procedures (First paediatric cardiologist): Atrial septostomy, pulmonary valve valvuloplasty', 'Cardiology / Congenital'),
    '1291': ('Use of balloon procedure as in Item 1290: Second paediatric cardiologist', 'Cardiology / Congenital'),
    '1292': ('Multi-slice computed tomography coronary angiography: Own equipment', 'Cardiology / Imaging'),
    '1294': ('Patent ductus arteriosus', 'Cardiology / Congenital'),
    '1295': ('Pericardiectomy for constrictive pericarditis', 'Cardiology / Surgery'),
    '1296': ('Fractional flow reserve (FFR): First vessel (add-on code)', 'Cardiology / Intervention'),
    '1297': ('Coarctation of aorta', 'Cardiology / Congenital'),
    '1298': ('Fractional flow reserve (FFR): Each additional vessel (add-on code)', 'Cardiology / Intervention'),
    '1299': ('Systemo-pulmonary anastomosis', 'Cardiology / Congenital'),
}

import json

result = []
for code in sorted(found.keys()):
    if code not in existing:
        desc, cat = found[code]
        c = int(code)
        if (300 <= c <= 499) or (500 <= c <= 799) or (1200 <= c <= 1299):
            result.append({"code": code, "desc": desc, "category": cat})

# Remove duplicate 0533 entry (same as 0513, from osteotomy list)
seen = set()
deduped = []
for item in result:
    key = item['code']
    if key not in seen:
        seen.add(key)
        deduped.append(item)

print(json.dumps(deduped, indent=2))
import sys
print(f"\nTotal new codes: {len(deduped)}", file=sys.stderr)
