# Common ICD-10-CM codes for general practice
# Format: (code, description)
ICD10_CODES = [
    # ── Chapter A: Infectious and parasitic diseases ──────────────────────────
    ("A00.9",  "Cholera, unspecified"),
    ("A01.0",  "Typhoid fever"),
    ("A02.0",  "Salmonella enteritis"),
    ("A03.9",  "Shigellosis, unspecified"),
    ("A04.7",  "Enterocolitis due to Clostridium difficile"),
    ("A06.0",  "Acute amoebic dysentery"),
    ("A09",    "Infectious gastroenteritis and colitis, unspecified"),
    ("A15.0",  "Tuberculosis of lung, confirmed by sputum microscopy"),
    ("A15.9",  "Respiratory tuberculosis, unspecified"),
    ("A16.2",  "Tuberculosis of lung, without bacteriological confirmation"),
    ("A16.9",  "Respiratory tuberculosis unspecified, without bacteriological confirmation"),
    ("A17.0",  "Tuberculous meningitis"),
    ("A18.0",  "Tuberculosis of bones and joints"),
    ("A19.9",  "Miliary tuberculosis, unspecified"),
    ("A36.0",  "Pharyngeal diphtheria"),
    ("A37.0",  "Whooping cough due to Bordetella pertussis"),
    ("A38",    "Scarlet fever"),
    ("A40.9",  "Streptococcal septicaemia, unspecified"),
    ("A41.9",  "Septicaemia, unspecified"),
    ("A46",    "Erysipelas"),
    ("A49.0",  "Staphylococcal infection, unspecified"),
    ("A49.1",  "Streptococcal infection, unspecified"),
    ("A51.0",  "Primary genital syphilis"),
    ("A51.3",  "Secondary syphilis of skin and mucous membranes"),
    ("A53.9",  "Syphilis, unspecified"),
    ("A54.9",  "Gonorrhoea, unspecified"),
    ("A56.0",  "Chlamydial infection of lower genitourinary tract"),
    ("A56.2",  "Chlamydial infection of genitourinary tract, unspecified"),
    ("A57",    "Chancroid"),
    ("A59.0",  "Urogenital trichomoniasis"),
    ("A60.0",  "Herpesviral infection of genitalia and urogenital tract"),
    ("A63.0",  "Anogenital (venereal) warts"),
    ("A64",    "Unspecified sexually transmitted disease"),
    ("A80.9",  "Acute poliomyelitis, unspecified"),
    ("A87.9",  "Viral meningitis, unspecified"),
    ("A90",    "Dengue fever"),
    ("A91",    "Dengue haemorrhagic fever"),

    # ── Chapter B: Viral, parasitic, and fungal diseases ─────────────────────
    ("B00.1",  "Herpesviral vesicular dermatitis (cold sore / herpes simplex)"),
    ("B00.4",  "Herpesviral encephalitis"),
    ("B00.9",  "Herpesviral infection, unspecified"),
    ("B01.9",  "Varicella (chickenpox) without complication"),
    ("B02.9",  "Herpes zoster (shingles) without complication"),
    ("B05.9",  "Measles without complication"),
    ("B06.9",  "Rubella without complication"),
    ("B07",    "Viral warts"),
    ("B08.1",  "Molluscum contagiosum"),
    ("B15.9",  "Acute hepatitis A without hepatic coma"),
    ("B16.9",  "Acute hepatitis B without delta-agent and without hepatic coma"),
    ("B18.1",  "Chronic viral hepatitis B without delta-agent"),
    ("B18.2",  "Chronic viral hepatitis C"),
    ("B19.9",  "Unspecified viral hepatitis without hepatic coma"),
    ("B20",    "Human immunodeficiency virus (HIV) disease"),
    ("B24",    "Unspecified HIV disease"),
    ("B26.9",  "Mumps without complication"),
    ("B27.0",  "Infectious mononucleosis (glandular fever)"),
    ("B27.9",  "Infectious mononucleosis, unspecified"),
    ("B35.1",  "Tinea unguium (onychomycosis / fungal nail)"),
    ("B35.3",  "Tinea pedis (athlete's foot)"),
    ("B35.4",  "Tinea corporis (ringworm of body)"),
    ("B35.6",  "Tinea cruris (jock itch / groin ringworm)"),
    ("B36.0",  "Pityriasis versicolor"),
    ("B37.0",  "Candidal stomatitis (oral thrush)"),
    ("B37.3",  "Vaginal candidiasis (thrush)"),
    ("B37.4",  "Candidiasis of other urogenital sites"),
    ("B37.9",  "Candidiasis, unspecified"),
    ("B50.9",  "Plasmodium falciparum malaria, unspecified"),
    ("B51.9",  "Plasmodium vivax malaria without complication"),
    ("B54",    "Unspecified malaria"),
    ("B76.0",  "Hookworm infection (Ancylostomiasis)"),
    ("B77.9",  "Ascariasis, unspecified"),
    ("B80",    "Enterobiasis (pinworm / threadworm infection)"),
    ("B82.9",  "Intestinal parasitism, unspecified"),
    ("B86",    "Scabies"),

    # ── Chapter C: Malignant neoplasms (selected) ─────────────────────────────
    ("C18.9",  "Malignant neoplasm of colon, unspecified"),
    ("C20",    "Malignant neoplasm of rectum"),
    ("C22.0",  "Hepatocellular carcinoma (liver cell carcinoma)"),
    ("C34.9",  "Malignant neoplasm of bronchus or lung, unspecified"),
    ("C50.9",  "Malignant neoplasm of breast, unspecified"),
    ("C53.9",  "Malignant neoplasm of cervix uteri, unspecified"),
    ("C61",    "Malignant neoplasm of prostate"),
    ("C73",    "Malignant neoplasm of thyroid gland"),
    ("C80.9",  "Malignant neoplasm, primary site unspecified"),
    ("C91.0",  "Acute lymphoblastic leukaemia"),
    ("C92.0",  "Acute myeloid leukaemia"),

    # ── Chapter D: Benign neoplasms / blood disorders ─────────────────────────
    ("D50.9",  "Iron deficiency anaemia, unspecified"),
    ("D51.9",  "Vitamin B12 deficiency anaemia, unspecified"),
    ("D52.9",  "Folate deficiency anaemia, unspecified"),
    ("D53.9",  "Nutritional anaemia, unspecified"),
    ("D57.0",  "Sickle-cell anaemia with crisis"),
    ("D57.1",  "Sickle-cell anaemia without crisis"),
    ("D62",    "Acute posthemorrhagic anaemia"),
    ("D64.9",  "Anaemia, unspecified"),
    ("D69.3",  "Immune thrombocytopenic purpura (ITP)"),

    # ── Chapter E: Endocrine, nutritional and metabolic diseases ─────────────
    ("E03.9",  "Hypothyroidism, unspecified"),
    ("E04.2",  "Non-toxic multinodular goitre"),
    ("E05.0",  "Thyrotoxicosis with diffuse goitre (Graves disease)"),
    ("E05.9",  "Thyrotoxicosis, unspecified (hyperthyroidism)"),
    ("E06.3",  "Autoimmune thyroiditis (Hashimoto's thyroiditis)"),
    ("E10.9",  "Type 1 diabetes mellitus without complications"),
    ("E11.4",  "Type 2 diabetes mellitus with neurological complications (diabetic neuropathy)"),
    ("E11.5",  "Type 2 diabetes mellitus with peripheral circulatory complications"),
    ("E11.6",  "Type 2 diabetes mellitus with other specified complications"),
    ("E11.7",  "Type 2 diabetes mellitus with multiple complications"),
    ("E11.9",  "Type 2 diabetes mellitus without complications"),
    ("E14.9",  "Unspecified diabetes mellitus without complications"),
    ("E16.0",  "Drug-induced hypoglycaemia without coma"),
    ("E16.2",  "Hypoglycaemia, unspecified"),
    ("E20.9",  "Hypoparathyroidism, unspecified"),
    ("E21.0",  "Primary hyperparathyroidism"),
    ("E22.1",  "Hyperprolactinaemia"),
    ("E23.2",  "Diabetes insipidus"),
    ("E27.1",  "Primary adrenocortical insufficiency (Addison's disease)"),
    ("E28.2",  "Polycystic ovarian syndrome (PCOS)"),
    ("E29.1",  "Testicular hypofunction (hypogonadism)"),
    ("E34.9",  "Endocrine disorder, unspecified"),
    ("E40",    "Kwashiorkor"),
    ("E41",    "Nutritional marasmus"),
    ("E44.0",  "Moderate protein-energy malnutrition"),
    ("E50.9",  "Vitamin A deficiency, unspecified"),
    ("E53.8",  "Deficiency of other specified B group vitamins"),
    ("E55.9",  "Vitamin D deficiency, unspecified (rickets)"),
    ("E61.0",  "Copper deficiency"),
    ("E66.0",  "Morbid (severe) obesity due to excess calories"),
    ("E66.9",  "Obesity, unspecified"),
    ("E78.0",  "Pure hypercholesterolaemia"),
    ("E78.1",  "Pure hypertriglyceridaemia"),
    ("E78.2",  "Mixed hyperlipidaemia"),
    ("E78.5",  "Hyperlipidaemia, unspecified (dyslipidaemia)"),
    ("E79.0",  "Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease"),
    ("E83.1",  "Disorders of iron metabolism (haemochromatosis)"),
    ("E86",    "Volume depletion (dehydration)"),
    ("E87.1",  "Hypo-osmolality and hyponatraemia"),
    ("E87.5",  "Hyperkalaemia"),
    ("E87.6",  "Hypokalaemia"),

    # ── Chapter F: Mental and behavioural disorders ───────────────────────────
    ("F00.1",  "Dementia in Alzheimer's disease with late onset"),
    ("F01.3",  "Mixed cortical and subcortical vascular dementia"),
    ("F02.3",  "Dementia in Parkinson's disease"),
    ("F05.9",  "Delirium, unspecified"),
    ("F10.1",  "Alcohol use disorder — harmful use"),
    ("F10.2",  "Alcohol dependence syndrome"),
    ("F10.3",  "Alcohol withdrawal state"),
    ("F11.1",  "Opioid use disorder"),
    ("F12.1",  "Cannabis use disorder"),
    ("F17.1",  "Tobacco use disorder"),
    ("F17.2",  "Nicotine dependence"),
    ("F19.1",  "Mental disorders due to multiple drug use"),
    ("F20.9",  "Schizophrenia, unspecified"),
    ("F25.9",  "Schizoaffective disorder, unspecified"),
    ("F31.9",  "Bipolar affective disorder, unspecified"),
    ("F32.0",  "Mild depressive episode"),
    ("F32.1",  "Moderate depressive episode"),
    ("F32.2",  "Severe depressive episode without psychotic symptoms"),
    ("F32.9",  "Depressive episode, unspecified"),
    ("F33.0",  "Recurrent depressive disorder, current episode mild"),
    ("F33.1",  "Recurrent depressive disorder, current episode moderate"),
    ("F33.9",  "Recurrent depressive disorder, unspecified"),
    ("F40.0",  "Agoraphobia"),
    ("F40.1",  "Social phobia (social anxiety disorder)"),
    ("F40.9",  "Phobic anxiety disorder, unspecified"),
    ("F41.0",  "Panic disorder (episodic paroxysmal anxiety)"),
    ("F41.1",  "Generalised anxiety disorder (GAD)"),
    ("F41.2",  "Mixed anxiety and depressive disorder"),
    ("F41.9",  "Anxiety disorder, unspecified"),
    ("F42.9",  "Obsessive-compulsive disorder (OCD), unspecified"),
    ("F43.0",  "Acute stress reaction"),
    ("F43.1",  "Post-traumatic stress disorder (PTSD)"),
    ("F43.2",  "Adjustment disorders"),
    ("F44.9",  "Dissociative (conversion) disorder, unspecified"),
    ("F45.0",  "Somatization disorder"),
    ("F48.0",  "Neurasthenia (chronic fatigue syndrome)"),
    ("F50.0",  "Anorexia nervosa"),
    ("F50.2",  "Bulimia nervosa"),
    ("F51.0",  "Non-organic insomnia"),
    ("F60.3",  "Emotionally unstable personality disorder (borderline)"),
    ("F70.9",  "Mild intellectual disability, unspecified"),
    ("F84.0",  "Childhood autism (autism spectrum disorder)"),
    ("F90.0",  "Attention deficit hyperactivity disorder (ADHD)"),
    ("F91.9",  "Conduct disorder, unspecified"),
    ("F98.0",  "Non-organic enuresis (bedwetting)"),
    ("F99",    "Mental disorder, not otherwise specified"),

    # ── Chapter G: Nervous system ─────────────────────────────────────────────
    ("G00.9",  "Bacterial meningitis, unspecified"),
    ("G03.9",  "Meningitis, unspecified"),
    ("G04.9",  "Encephalitis, myelitis and encephalomyelitis, unspecified"),
    ("G20",    "Parkinson's disease"),
    ("G25.0",  "Essential tremor"),
    ("G30.9",  "Alzheimer's disease, unspecified"),
    ("G35",    "Multiple sclerosis"),
    ("G40.9",  "Epilepsy, unspecified"),
    ("G41.9",  "Status epilepticus, unspecified"),
    ("G43.0",  "Migraine without aura (common migraine)"),
    ("G43.1",  "Migraine with aura (classical migraine)"),
    ("G43.9",  "Migraine, unspecified"),
    ("G44.2",  "Tension-type headache"),
    ("G45.9",  "Transient cerebral ischaemic attack (TIA), unspecified"),
    ("G47.0",  "Insomnia (disorder of initiating and maintaining sleep)"),
    ("G47.3",  "Sleep apnoea (obstructive sleep apnoea)"),
    ("G50.0",  "Trigeminal neuralgia"),
    ("G51.0",  "Bell's palsy (facial nerve palsy)"),
    ("G54.2",  "Cervical root disorders (cervical radiculopathy)"),
    ("G54.4",  "Lumbosacral root disorders (lumbar radiculopathy)"),
    ("G56.0",  "Carpal tunnel syndrome"),
    ("G57.0",  "Lesion of sciatic nerve (sciatica)"),
    ("G61.0",  "Guillain-Barré syndrome"),
    ("G62.0",  "Drug-induced polyneuropathy"),
    ("G62.9",  "Polyneuropathy, unspecified"),
    ("G63.2",  "Diabetic polyneuropathy"),
    ("G71.0",  "Muscular dystrophy"),
    ("G89.2",  "Chronic pain syndrome"),
    ("G93.1",  "Anoxic brain damage"),
    ("G93.3",  "Post-viral fatigue syndrome"),
    ("G96.9",  "Disorder of central nervous system, unspecified"),

    # ── Chapter H: Eye diseases ───────────────────────────────────────────────
    ("H00.0",  "Hordeolum (stye)"),
    ("H01.0",  "Blepharitis"),
    ("H04.3",  "Dacryocystitis (lacrimal sac infection)"),
    ("H10.0",  "Mucopurulent conjunctivitis"),
    ("H10.1",  "Acute atopic conjunctivitis (allergic conjunctivitis)"),
    ("H10.9",  "Conjunctivitis, unspecified"),
    ("H11.3",  "Subconjunctival haemorrhage"),
    ("H16.0",  "Corneal ulcer"),
    ("H20.0",  "Acute and subacute iridocyclitis (uveitis)"),
    ("H25.9",  "Senile cataract, unspecified"),
    ("H33.0",  "Retinal detachment with retinal break"),
    ("H35.3",  "Degeneration of macula and posterior pole (macular degeneration)"),
    ("H40.9",  "Glaucoma, unspecified"),
    ("H52.0",  "Hypermetropia (long-sightedness)"),
    ("H52.1",  "Myopia (short-sightedness)"),
    ("H52.2",  "Astigmatism"),
    ("H52.4",  "Presbyopia"),
    ("H54.7",  "Unspecified visual loss"),

    # ── Chapter H: Ear diseases ───────────────────────────────────────────────
    ("H60.3",  "Other infective otitis externa (swimmer's ear)"),
    ("H60.9",  "Otitis externa, unspecified"),
    ("H65.0",  "Acute serous otitis media"),
    ("H65.9",  "Non-suppurative otitis media, unspecified"),
    ("H66.0",  "Acute suppurative otitis media"),
    ("H66.9",  "Otitis media, unspecified"),
    ("H72.9",  "Perforation of tympanic membrane, unspecified"),
    ("H81.0",  "Ménière's disease"),
    ("H81.3",  "Other peripheral vertigo (benign positional vertigo)"),
    ("H81.4",  "Vertigo of central origin"),
    ("H83.0",  "Labyrinthitis"),
    ("H90.3",  "Sensorineural hearing loss, bilateral"),
    ("H91.9",  "Hearing loss, unspecified"),
    ("H92.0",  "Otalgia (ear pain)"),
    ("H93.1",  "Tinnitus"),

    # ── Chapter I: Circulatory diseases ──────────────────────────────────────
    ("I10",    "Essential (primary) hypertension"),
    ("I11.9",  "Hypertensive heart disease without heart failure"),
    ("I12.9",  "Hypertensive renal disease without renal failure"),
    ("I13.1",  "Hypertensive heart and renal disease without heart failure"),
    ("I20.0",  "Unstable angina"),
    ("I20.9",  "Angina pectoris, unspecified (stable angina)"),
    ("I21.0",  "Acute transmural myocardial infarction of anterior wall"),
    ("I21.9",  "Acute myocardial infarction (heart attack), unspecified"),
    ("I25.1",  "Atherosclerotic heart disease of native coronary artery"),
    ("I25.9",  "Chronic ischaemic heart disease, unspecified"),
    ("I26.9",  "Pulmonary embolism without acute cor pulmonale"),
    ("I27.0",  "Primary pulmonary hypertension"),
    ("I34.0",  "Mitral valve regurgitation"),
    ("I35.0",  "Aortic valve stenosis"),
    ("I42.0",  "Dilated cardiomyopathy"),
    ("I42.9",  "Cardiomyopathy, unspecified"),
    ("I48",    "Atrial fibrillation and flutter"),
    ("I49.4",  "Other and unspecified premature depolarization (ectopic beats / palpitations)"),
    ("I50.0",  "Congestive heart failure"),
    ("I50.9",  "Heart failure, unspecified"),
    ("I60.9",  "Subarachnoid haemorrhage, unspecified"),
    ("I61.9",  "Intracerebral haemorrhage, unspecified"),
    ("I63.9",  "Cerebral infarction (ischaemic stroke), unspecified"),
    ("I64",    "Stroke, not specified as haemorrhage or infarction"),
    ("I69.3",  "Sequelae of cerebral infarction (post-stroke)"),
    ("I70.2",  "Atherosclerosis of arteries of extremities (peripheral arterial disease)"),
    ("I73.0",  "Raynaud's syndrome"),
    ("I80.2",  "Deep vein thrombosis (DVT) of lower extremity"),
    ("I83.9",  "Varicose veins of lower extremities without ulcer or inflammation"),
    ("I84.9",  "Haemorrhoids, unspecified (piles)"),
    ("I87.2",  "Venous insufficiency (chronic peripheral)"),

    # ── Chapter J: Respiratory diseases ──────────────────────────────────────
    ("J00",    "Acute nasopharyngitis (common cold)"),
    ("J01.0",  "Acute maxillary sinusitis"),
    ("J01.1",  "Acute frontal sinusitis"),
    ("J01.9",  "Acute sinusitis, unspecified"),
    ("J02.0",  "Streptococcal pharyngitis (strep throat)"),
    ("J02.9",  "Acute pharyngitis, unspecified (sore throat)"),
    ("J03.0",  "Streptococcal tonsillitis"),
    ("J03.9",  "Acute tonsillitis, unspecified"),
    ("J04.0",  "Acute laryngitis"),
    ("J04.2",  "Acute laryngotracheitis"),
    ("J05.0",  "Acute obstructive laryngitis (croup)"),
    ("J06.0",  "Acute laryngopharyngitis"),
    ("J06.9",  "Acute upper respiratory infection, unspecified (URTI)"),
    ("J10.1",  "Influenza with other respiratory manifestations, influenza virus identified"),
    ("J11.0",  "Influenza with pneumonia, virus not identified"),
    ("J11.1",  "Influenza with other respiratory manifestations, virus not identified"),
    ("J18.0",  "Bronchopneumonia, unspecified"),
    ("J18.1",  "Lobar pneumonia, unspecified"),
    ("J18.9",  "Pneumonia, unspecified"),
    ("J20.9",  "Acute bronchitis, unspecified"),
    ("J21.9",  "Acute bronchiolitis, unspecified"),
    ("J30.0",  "Vasomotor rhinitis"),
    ("J30.1",  "Allergic rhinitis due to pollen (hay fever)"),
    ("J30.4",  "Allergic rhinitis, unspecified"),
    ("J31.0",  "Chronic rhinitis"),
    ("J32.0",  "Chronic maxillary sinusitis"),
    ("J32.9",  "Chronic sinusitis, unspecified"),
    ("J33.9",  "Nasal polyp, unspecified"),
    ("J35.0",  "Chronic tonsillitis"),
    ("J35.1",  "Hypertrophy of tonsils"),
    ("J36",    "Peritonsillar abscess (quinsy)"),
    ("J37.0",  "Chronic laryngitis"),
    ("J39.9",  "Disease of upper respiratory tract, unspecified"),
    ("J40",    "Bronchitis, not specified as acute or chronic"),
    ("J42",    "Unspecified chronic bronchitis"),
    ("J43.9",  "Emphysema, unspecified"),
    ("J44.0",  "COPD with acute lower respiratory infection"),
    ("J44.1",  "COPD with acute exacerbation"),
    ("J44.9",  "Chronic obstructive pulmonary disease (COPD), unspecified"),
    ("J45.0",  "Predominantly allergic asthma"),
    ("J45.1",  "Non-allergic asthma"),
    ("J45.9",  "Asthma, unspecified"),
    ("J46",    "Status asthmaticus"),
    ("J47",    "Bronchiectasis"),
    ("J81",    "Pulmonary oedema"),
    ("J84.9",  "Interstitial pulmonary disease, unspecified"),
    ("J90",    "Pleural effusion"),
    ("J93.9",  "Pneumothorax, unspecified"),
    ("J96.0",  "Acute respiratory failure"),
    ("J96.9",  "Respiratory failure, unspecified"),

    # ── Chapter K: Digestive diseases ────────────────────────────────────────
    ("K02.9",  "Dental caries, unspecified"),
    ("K05.1",  "Chronic gingivitis"),
    ("K05.3",  "Chronic periodontitis"),
    ("K12.0",  "Recurrent oral aphthae (mouth ulcers)"),
    ("K12.1",  "Other forms of stomatitis"),
    ("K20",    "Oesophagitis"),
    ("K21.0",  "Gastro-oesophageal reflux disease with oesophagitis (GERD)"),
    ("K21.9",  "Gastro-oesophageal reflux disease without oesophagitis (GORD)"),
    ("K25.9",  "Gastric ulcer, unspecified"),
    ("K26.9",  "Duodenal ulcer, unspecified"),
    ("K27.9",  "Peptic ulcer, site unspecified"),
    ("K29.5",  "Chronic gastritis, unspecified"),
    ("K29.6",  "Gastritis due to Helicobacter pylori"),
    ("K29.7",  "Gastritis, unspecified"),
    ("K30",    "Functional dyspepsia"),
    ("K35.8",  "Acute appendicitis with other complications"),
    ("K37",    "Unspecified appendicitis"),
    ("K40.9",  "Inguinal hernia without obstruction or gangrene, unspecified"),
    ("K41.9",  "Femoral hernia without obstruction or gangrene, unspecified"),
    ("K42.9",  "Umbilical hernia without obstruction or gangrene"),
    ("K50.9",  "Crohn's disease (regional enteritis), unspecified"),
    ("K51.9",  "Ulcerative colitis, unspecified"),
    ("K52.9",  "Non-infective gastroenteritis and colitis, unspecified"),
    ("K57.3",  "Diverticular disease of large intestine without perforation or abscess"),
    ("K57.9",  "Diverticular disease of intestine, unspecified"),
    ("K58.0",  "Irritable bowel syndrome (IBS) with diarrhoea"),
    ("K58.9",  "Irritable bowel syndrome (IBS) without diarrhoea"),
    ("K59.0",  "Constipation"),
    ("K59.1",  "Functional diarrhoea"),
    ("K62.5",  "Haemorrhage of anus and rectum (rectal bleeding)"),
    ("K70.3",  "Alcoholic cirrhosis of liver"),
    ("K74.6",  "Other and unspecified cirrhosis of liver"),
    ("K76.0",  "Fatty liver (non-alcoholic fatty liver disease, NAFLD)"),
    ("K80.2",  "Calculus of gallbladder without cholecystitis (gallstones)"),
    ("K81.0",  "Acute cholecystitis"),
    ("K81.9",  "Cholecystitis, unspecified"),
    ("K85.9",  "Acute pancreatitis, unspecified"),
    ("K86.1",  "Other chronic pancreatitis"),
    ("K90.0",  "Coeliac disease (gluten-sensitive enteropathy)"),
    ("K92.1",  "Melaena (black tarry stool)"),
    ("K92.2",  "Gastrointestinal haemorrhage, unspecified"),

    # ── Chapter L: Skin diseases ──────────────────────────────────────────────
    ("L01.0",  "Impetigo"),
    ("L01.9",  "Impetigo, unspecified"),
    ("L02.9",  "Cutaneous abscess, furuncle and carbuncle, unspecified"),
    ("L03.1",  "Cellulitis of other parts of limb"),
    ("L03.9",  "Cellulitis, unspecified"),
    ("L08.0",  "Pyoderma"),
    ("L20.9",  "Atopic dermatitis (eczema), unspecified"),
    ("L21.0",  "Seborrhoeic capitis (cradle cap / dandruff)"),
    ("L21.9",  "Seborrhoeic dermatitis, unspecified"),
    ("L23.9",  "Allergic contact dermatitis, unspecified cause"),
    ("L24.9",  "Irritant contact dermatitis, unspecified cause"),
    ("L25.9",  "Unspecified contact dermatitis, unspecified cause"),
    ("L27.0",  "Generalised skin eruption due to drugs (drug rash)"),
    ("L27.1",  "Localised skin eruption due to drugs"),
    ("L29.9",  "Pruritus, unspecified (generalised itching)"),
    ("L30.9",  "Dermatitis, unspecified"),
    ("L40.0",  "Psoriasis vulgaris"),
    ("L40.9",  "Psoriasis, unspecified"),
    ("L43.9",  "Lichen planus, unspecified"),
    ("L50.0",  "Allergic urticaria (hives)"),
    ("L50.9",  "Urticaria, unspecified"),
    ("L51.9",  "Erythema multiforme, unspecified"),
    ("L52",    "Erythema nodosum"),
    ("L55.9",  "Sunburn, unspecified"),
    ("L57.0",  "Actinic keratosis"),
    ("L60.0",  "Ingrowing nail"),
    ("L63.9",  "Alopecia areata, unspecified"),
    ("L64.9",  "Androgenic alopecia (male-pattern baldness)"),
    ("L70.0",  "Acne vulgaris"),
    ("L71.9",  "Rosacea, unspecified"),
    ("L72.0",  "Epidermal cyst (sebaceous cyst)"),
    ("L82",    "Seborrhoeic keratosis"),
    ("L84",    "Corns and callosities"),
    ("L85.3",  "Xerosis cutis (dry skin)"),
    ("L89.9",  "Pressure sore (decubitus ulcer), unspecified"),
    ("L91.0",  "Hypertrophic scar (keloid)"),
    ("L97",    "Venous, arterial, or mixed leg ulcer"),
    ("L98.4",  "Chronic ulcer of skin, not elsewhere classified"),

    # ── Chapter M: Musculoskeletal diseases ──────────────────────────────────
    ("M06.9",  "Rheumatoid arthritis, unspecified"),
    ("M10.0",  "Idiopathic gout"),
    ("M10.9",  "Gout, unspecified"),
    ("M13.9",  "Arthritis, unspecified"),
    ("M15.0",  "Primary generalised osteoarthritis"),
    ("M16.9",  "Hip osteoarthritis (coxarthrosis), unspecified"),
    ("M17.1",  "Primary knee osteoarthritis (gonarthrosis)"),
    ("M17.9",  "Knee osteoarthritis, unspecified"),
    ("M19.9",  "Arthrosis, unspecified"),
    ("M20.1",  "Hallux valgus (bunion)"),
    ("M25.5",  "Pain in joint"),
    ("M32.9",  "Systemic lupus erythematosus (SLE), unspecified"),
    ("M35.0",  "Sjögren's syndrome"),
    ("M35.3",  "Polymyalgia rheumatica"),
    ("M40.0",  "Postural kyphosis"),
    ("M41.9",  "Scoliosis, unspecified"),
    ("M43.6",  "Torticollis (wry neck)"),
    ("M45",    "Ankylosing spondylitis"),
    ("M47.8",  "Cervical spondylosis"),
    ("M47.9",  "Spondylosis, unspecified"),
    ("M48.0",  "Spinal stenosis"),
    ("M50.1",  "Cervical disc disorder with radiculopathy"),
    ("M51.1",  "Lumbar disc degeneration with radiculopathy"),
    ("M51.9",  "Unspecified intervertebral disc degeneration"),
    ("M54.2",  "Cervicalgia (neck pain)"),
    ("M54.3",  "Sciatica"),
    ("M54.4",  "Lumbago with sciatica"),
    ("M54.5",  "Low back pain (lumbago)"),
    ("M54.9",  "Dorsalgia (back pain), unspecified"),
    ("M60.9",  "Myositis, unspecified"),
    ("M65.9",  "Synovitis and tenosynovitis, unspecified"),
    ("M72.2",  "Plantar fasciitis (heel pain)"),
    ("M75.1",  "Rotator cuff syndrome (shoulder impingement)"),
    ("M75.3",  "Calcific tendinitis of shoulder"),
    ("M75.5",  "Bursitis of shoulder"),
    ("M76.5",  "Patellar tendinitis (jumper's knee)"),
    ("M77.0",  "Medial epicondylitis (golfer's elbow)"),
    ("M77.1",  "Lateral epicondylitis (tennis elbow)"),
    ("M77.3",  "Calcaneal spur"),
    ("M79.0",  "Rheumatism, unspecified"),
    ("M79.1",  "Myalgia (muscle pain)"),
    ("M79.2",  "Neuralgia and neuritis, unspecified"),
    ("M79.7",  "Fibromyalgia"),
    ("M81.0",  "Postmenopausal osteoporosis"),
    ("M81.9",  "Osteoporosis, unspecified"),
    ("M86.9",  "Osteomyelitis, unspecified"),

    # ── Chapter N: Genitourinary diseases ────────────────────────────────────
    ("N10",    "Acute tubulo-interstitial nephritis (acute pyelonephritis)"),
    ("N11.9",  "Chronic pyelonephritis, unspecified"),
    ("N17.9",  "Acute renal failure (acute kidney injury), unspecified"),
    ("N18.9",  "Chronic kidney disease (CKD), unspecified"),
    ("N20.0",  "Calculus of kidney (kidney stones)"),
    ("N20.9",  "Urinary calculus, unspecified"),
    ("N23",    "Unspecified renal colic"),
    ("N28.9",  "Disorder of kidney and ureter, unspecified"),
    ("N30.0",  "Acute cystitis"),
    ("N30.9",  "Cystitis, unspecified"),
    ("N34.1",  "Non-specific urethritis"),
    ("N39.0",  "Urinary tract infection (UTI), site not specified"),
    ("N39.3",  "Stress urinary incontinence"),
    ("N39.4",  "Other specified urinary incontinence"),
    ("N40",    "Benign prostatic hyperplasia (BPH)"),
    ("N41.0",  "Acute prostatitis"),
    ("N41.1",  "Chronic prostatitis"),
    ("N41.9",  "Inflammatory disease of prostate, unspecified"),
    ("N45.9",  "Orchitis and epididymitis, unspecified"),
    ("N46",    "Male infertility"),
    ("N47.1",  "Phimosis"),
    ("N60.1",  "Fibrocystic breast disease (diffuse cystic mastopathy)"),
    ("N63",    "Unspecified lump in breast"),
    ("N70.0",  "Acute salpingitis and oophoritis"),
    ("N70.9",  "Salpingitis and oophoritis, unspecified (PID)"),
    ("N72",    "Cervicitis (inflammatory disease of cervix uteri)"),
    ("N73.9",  "Female pelvic inflammatory disease, unspecified"),
    ("N75.0",  "Cyst of Bartholin's gland"),
    ("N76.0",  "Acute vaginitis"),
    ("N76.1",  "Subacute and chronic vaginitis"),
    ("N80.0",  "Endometriosis of uterus (adenomyosis)"),
    ("N80.9",  "Endometriosis, unspecified"),
    ("N83.0",  "Follicular cyst of ovary"),
    ("N83.2",  "Other and unspecified ovarian cysts"),
    ("N84.0",  "Polyp of corpus uteri (endometrial polyp)"),
    ("N87.9",  "Dysplasia of cervix uteri, unspecified (CIN)"),
    ("N91.2",  "Amenorrhoea, unspecified"),
    ("N92.0",  "Menorrhagia (heavy menstrual bleeding) with regular cycle"),
    ("N92.6",  "Irregular menstruation, unspecified"),
    ("N94.4",  "Primary dysmenorrhoea (painful periods)"),
    ("N94.5",  "Secondary dysmenorrhoea"),
    ("N94.6",  "Dysmenorrhoea, unspecified"),
    ("N95.1",  "Menopausal and female climacteric states (menopause)"),
    ("N97.9",  "Female infertility, unspecified"),

    # ── Chapter O: Pregnancy, childbirth and puerperium ──────────────────────
    ("O00.9",  "Ectopic pregnancy, unspecified"),
    ("O02.1",  "Missed abortion"),
    ("O03.9",  "Spontaneous abortion (miscarriage), complete or unspecified, without complication"),
    ("O10.0",  "Pre-existing essential hypertension complicating pregnancy"),
    ("O13",    "Gestational (pregnancy-induced) hypertension"),
    ("O14.0",  "Mild to moderate pre-eclampsia"),
    ("O14.1",  "Severe pre-eclampsia"),
    ("O14.9",  "Pre-eclampsia, unspecified"),
    ("O20.0",  "Threatened abortion"),
    ("O21.0",  "Mild hyperemesis gravidarum"),
    ("O21.9",  "Vomiting of pregnancy, unspecified"),
    ("O24.9",  "Gestational diabetes mellitus"),
    ("O30.0",  "Twin pregnancy"),
    ("O42.9",  "Premature rupture of membranes, unspecified"),
    ("O60.0",  "Preterm labour without delivery"),
    ("O80",    "Single spontaneous delivery (normal vaginal delivery)"),
    ("O82.0",  "Delivery by elective caesarean section"),
    ("O91.2",  "Mastitis (non-purulent)"),
    ("O99.3",  "Mental disorders complicating pregnancy"),

    # ── Chapter R: Symptoms, signs and abnormal clinical findings ────────────
    ("R00.0",  "Tachycardia, unspecified (fast heart rate)"),
    ("R00.1",  "Bradycardia, unspecified (slow heart rate)"),
    ("R00.8",  "Palpitations (other and unspecified abnormalities of heart beat)"),
    ("R04.2",  "Haemoptysis (coughing up blood)"),
    ("R05",    "Cough"),
    ("R06.0",  "Dyspnoea (shortness of breath)"),
    ("R06.2",  "Wheezing"),
    ("R07.0",  "Pain in throat"),
    ("R07.1",  "Chest pain on breathing (pleuritic chest pain)"),
    ("R07.4",  "Chest pain, unspecified"),
    ("R10.0",  "Acute abdomen"),
    ("R10.1",  "Pain localised to upper abdomen (epigastric pain)"),
    ("R10.3",  "Pain localised to lower abdomen"),
    ("R10.4",  "Abdominal pain, unspecified"),
    ("R11",    "Nausea and vomiting"),
    ("R12",    "Heartburn"),
    ("R13",    "Dysphagia (difficulty swallowing)"),
    ("R14",    "Flatulence and related conditions (bloating / wind)"),
    ("R17",    "Unspecified jaundice (yellowing of skin)"),
    ("R18",    "Ascites"),
    ("R19.7",  "Diarrhoea, unspecified"),
    ("R20.2",  "Paraesthesia of skin (pins and needles / numbness)"),
    ("R22.9",  "Localised swelling, mass and lump, unspecified"),
    ("R25.2",  "Cramp and spasm"),
    ("R29.6",  "Tendency to fall"),
    ("R31",    "Unspecified haematuria (blood in urine)"),
    ("R32",    "Unspecified urinary incontinence"),
    ("R33",    "Retention of urine"),
    ("R35",    "Polyuria (excessive urination)"),
    ("R42",    "Dizziness and giddiness (vertigo)"),
    ("R50.9",  "Fever, unspecified (pyrexia)"),
    ("R51",    "Headache"),
    ("R52.9",  "Pain, unspecified"),
    ("R53",    "Malaise and fatigue (tiredness / lethargy / weakness)"),
    ("R55",    "Syncope and collapse (fainting / blackout)"),
    ("R56.8",  "Convulsions (seizures), unspecified"),
    ("R60.0",  "Localised oedema (swelling)"),
    ("R60.9",  "Oedema (swelling), unspecified"),
    ("R63.0",  "Anorexia (loss of appetite)"),
    ("R63.4",  "Abnormal weight loss"),
    ("R63.5",  "Abnormal weight gain"),
    ("R73.0",  "Abnormal glucose tolerance test (impaired glucose tolerance / pre-diabetes)"),
    ("R73.9",  "Hyperglycaemia, unspecified"),
    ("R79.8",  "Other specified abnormal findings of blood chemistry (elevated PSA)"),
    ("R82.0",  "Chyluria"),

    # ── Chapter S: Injuries (selected) ───────────────────────────────────────
    ("S00.9",  "Superficial injury of head, unspecified"),
    ("S01.9",  "Open wound of head, unspecified"),
    ("S06.0",  "Concussion"),
    ("S06.9",  "Intracranial injury, unspecified"),
    ("S13.4",  "Whiplash injury of cervical spine"),
    ("S22.4",  "Multiple fractures of ribs"),
    ("S42.0",  "Fracture of clavicle (broken collarbone)"),
    ("S42.2",  "Fracture of upper end of humerus (proximal humerus fracture)"),
    ("S43.0",  "Dislocation of shoulder joint"),
    ("S52.5",  "Fracture of lower end of radius (Colles fracture)"),
    ("S52.9",  "Fracture of forearm, unspecified"),
    ("S72.0",  "Fracture of neck of femur (hip fracture)"),
    ("S72.1",  "Pertrochanteric fracture"),
    ("S82.6",  "Fracture of lateral malleolus (ankle fracture)"),
    ("S83.2",  "Tear of meniscus, current injury"),
    ("S83.6",  "Sprain of knee"),
    ("S90.0",  "Contusion of ankle"),
    ("S93.4",  "Sprain of ankle"),

    # ── Chapter T: Poisoning, adverse effects ────────────────────────────────
    ("T14.0",  "Superficial injury of unspecified body region"),
    ("T14.1",  "Open wound of unspecified body region (laceration)"),
    ("T39.9",  "Poisoning by non-opioid analgesics, antipyretics and antirheumatics, unspecified"),
    ("T50.9",  "Poisoning by unspecified drug or medicament"),
    ("T51.0",  "Toxic effects of ethanol (alcohol poisoning)"),
    ("T74.1",  "Physical abuse"),
    ("T78.0",  "Anaphylactic shock due to adverse food reaction"),
    ("T78.1",  "Other adverse food reactions (food allergy)"),
    ("T78.4",  "Allergy, unspecified"),

    # ── Chapter Z: Factors influencing health status ──────────────────────────
    ("Z00.0",  "General medical examination (routine check-up)"),
    ("Z00.1",  "Routine child health examination (well-child visit)"),
    ("Z01.0",  "Examination of eyes and vision"),
    ("Z01.1",  "Examination of ears and hearing"),
    ("Z01.4",  "Gynaecological examination"),
    ("Z01.5",  "Diagnostic skin and sensitisation tests (allergy testing)"),
    ("Z02.0",  "Examination for admission to educational institution (school medical)"),
    ("Z02.1",  "Pre-employment examination"),
    ("Z03.9",  "Observation and evaluation for suspected diseases, unspecified"),
    ("Z12.3",  "Encounter for screening for malignant neoplasm of breast"),
    ("Z12.4",  "Encounter for screening for malignant neoplasm of cervix (cervical smear / Pap smear)"),
    ("Z23.8",  "Vaccination (other immunisations)"),
    ("Z25.1",  "Need for prophylactic vaccination against influenza (flu vaccine)"),
    ("Z30.0",  "General counselling and advice on contraception"),
    ("Z30.1",  "Insertion of intrauterine contraceptive device (IUCD / IUD)"),
    ("Z30.4",  "Surveillance of contraceptive drugs (contraceptive pill follow-up)"),
    ("Z33",    "Pregnant state, incidental"),
    ("Z34.0",  "Supervision of normal first pregnancy (antenatal visit — first pregnancy)"),
    ("Z34.9",  "Supervision of normal pregnancy, unspecified (antenatal visit)"),
    ("Z39.0",  "Care and examination immediately after delivery (postnatal visit)"),
    ("Z39.1",  "Care and examination of lactating mother (breastfeeding support)"),
    ("Z71.1",  "Person with feared condition in whom no diagnosis made (reassurance)"),
    ("Z82.4",  "Family history of ischaemic heart disease"),
    ("Z83.3",  "Family history of diabetes mellitus"),
    ("Z87.1",  "Personal history of tuberculosis"),
    ("Z88.0",  "Allergy status to penicillin"),
    ("Z88.9",  "Allergy status to unspecified drug (drug allergy)"),
    ("Z98.8",  "Other specified postsurgical states"),
]
