# Generated by Django 4.2.21 on 2026-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(help_text='Must match Patient.medical_aid_name (case-insensitive).', max_length=100, unique=True)),
                ('adapter', models.CharField(choices=[('manual', 'Manual / portal fallback (no direct API)')], default='manual', max_length=40)),
                ('endpoint_url', models.URLField(blank=True, default='', help_text='Scheme API base URL (or portal URL for the manual adapter).')),
                ('username_env', models.CharField(blank=True, default='', help_text='Name of the env var holding the API username/client id.', max_length=100)),
                ('password_env', models.CharField(blank=True, default='', help_text='Name of the env var holding the API password/secret.', max_length=100)),
                ('api_key_env', models.CharField(blank=True, default='', help_text='Name of the env var holding an API key/token, if used.', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Onboarding contacts, portal instructions, etc. Never paste secrets here.', null=True)),
            ],
            options={
                'verbose_name': 'Medical aid scheme config',
                'ordering': ['scheme_name'],
            },
        ),
    ]
