# Generated by Django 4.2.21 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_allergies_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alcohol_use',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Occasional', 'Occasional'), ('Moderate', 'Moderate'), ('Heavy', 'Heavy')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alt. phone (home/work)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_to_treat',
            field=models.BooleanField(default=False, verbose_name='Consent to treat given'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medication',
            field=models.TextField(blank=True, help_text='List current chronic medication and dosages', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dependant_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True, help_text='Relevant family medical history', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_type',
            field=models.CharField(choices=[('SA_ID', 'South African ID'), ('Passport', 'Passport Number')], default='SA_ID', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_aid_plan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan / option'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Next of kin name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Next of kin phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='popia_consent',
            field=models.BooleanField(default=False, verbose_name='POPIA consent given'),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Previous surgeries or hospitalisations with approximate dates', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='principal_member_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Principal member ID'),
        ),
        migrations.AddField(
            model_name='patient',
            name='principal_member_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Former', 'Former smoker'), ('Current', 'Current smoker')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='substance_use',
            field=models.TextField(blank=True, help_text='Any other substance use (optional)', null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Residential address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated (e.g. Penicillin, Sulfa drugs)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Comma-separated (e.g. Hypertension, Diabetes)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_aid_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical aid scheme'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Membership number'),
        ),
    ]
