# Generated by Django 4.2.21 on 2026-05-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_alcohol_use_patient_alt_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='employer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home language'),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Postal address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='work_address',
            field=models.TextField(blank=True, null=True, verbose_name='Work address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Work phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alt. phone (home)'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
