# Generated by Django 4.2.21 on 2026-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_employer_patient_home_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_address',
            field=models.TextField(blank=True, null=True, verbose_name='Next of kin address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Next of kin email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship to patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Referrer email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Referred by'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referrer phone/cell'),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Next of kin cell'),
        ),
    ]
