# Generated by Django 4.2.21 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_next_of_kin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residential_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Residential Code'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_cell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_id_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='I.D. Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_tel_h',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. (H)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_tel_w',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. (W)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10, null=True, verbose_name='Mr/Mrs/Miss'),
        ),
        migrations.AddField(
            model_name='patient',
            name='work_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Work Code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. (H)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='employer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Postal Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_address',
            field=models.TextField(blank=True, null=True, verbose_name='Work Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. (W)'),
        ),
    ]
