# Generated by Django 4.2.21 on 2026-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_postal_code_patient_residential_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='principal_member_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Main member ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='principal_member_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Main member name'),
        ),
    ]
