# Generated by Django 4.2.21 on 2026-07-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_role_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAidPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100, verbose_name='Medical aid scheme')),
                ('plan_name', models.CharField(blank=True, default='', help_text='Leave blank for a scheme-wide default.', max_length=100)),
                ('visits_per_year', models.PositiveIntegerField(verbose_name='GP visits covered per year')),
                ('warn_at', models.PositiveIntegerField(blank=True, help_text='Warn once this many visits are used. Default: 80% of the limit.', null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Medical aid plan (visit limits)',
                'verbose_name_plural': 'Medical aid plans (visit limits)',
                'ordering': ['scheme_name', 'plan_name'],
                'unique_together': {('scheme_name', 'plan_name')},
            },
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_hash', models.CharField(max_length=128, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='patients.patient')),
            ],
        ),
    ]
