# Generated by Django 4.2.21 on 2026-07-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0009_medicalaidplanconfig_biometrictemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0009_seed_mapfumo_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icd10_code', models.CharField(max_length=10, verbose_name='ICD-10 code')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive conditions are excluded from scoring.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('symptom', 'Symptom (reported)'), ('sign', 'Sign (observed)')], default='symptom', max_length=10)),
                ('synonyms', models.CharField(blank=True, help_text='Comma-separated alternates, e.g. "pyrexia, high temperature"', max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoryModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(choices=[('age_band', 'Age band (match value "min-max" years, e.g. "0-5" or "50-120")'), ('sex', 'Sex (match value "M", "F" or "O")'), ('chronic', 'Chronic condition on file (substring match, e.g. "diabetes")'), ('prior_episode', 'Prior episode of this condition (match value ignored)'), ('smoking', 'Smoking status (match value "Current" / "Former" / "Never")'), ('alcohol', 'Alcohol use (match value "Heavy" / "Moderate" / "Occasional" / "None")')], max_length=20)),
                ('match_value', models.CharField(blank=True, default='', help_text='What the factor must equal/contain — see factor choices.', max_length=100)),
                ('delta', models.SmallIntegerField(help_text='Score points added (confirming) or subtracted (contradicting).')),
                ('note', models.CharField(blank=True, help_text='Shown to the doctor as the plain-language "why".', max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_rules', to='diagnosis.condition')),
            ],
            options={
                'ordering': ['condition__name', 'factor'],
            },
        ),
        migrations.CreateModel(
            name='DifferentialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engine_version', models.CharField(max_length=10)),
                ('inputs', models.JSONField(help_text='Exact engine inputs: presenting/working symptom ids, free-text notes, history snapshot.')),
                ('output', models.JSONField(help_text='Ranked provisional-diagnosis list with full score breakdowns.')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_results', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_results', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomConditionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='1 (weak) – 10 (near-pathognomonic)')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_links', to='diagnosis.condition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links', to='diagnosis.symptom')),
            ],
            options={
                'ordering': ['condition__name', '-weight'],
                'unique_together': {('symptom', 'condition')},
            },
        ),
    ]
