# Generated by Django 4.2.21 on 2026-07-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_seed_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentialresult',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='differentialresult',
            name='confirmed_dx',
            field=models.JSONField(blank=True, help_text='Diagnoses the doctor promoted & confirmed: [{"code", "name", "source": "engine"|"manual"}].', null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='body_region',
            field=models.CharField(choices=[('head', 'Head & face'), ('throat', 'Throat & neck'), ('chest', 'Chest & respiratory'), ('abdomen', 'Abdomen & digestive'), ('pelvis', 'Pelvis & urinary'), ('limbs', 'Limbs, joints & back'), ('skin', 'Skin'), ('mental', 'Mood & sleep'), ('general', 'General / systemic')], default='general', help_text='Region used by the body-map picker in the consultation workspace.', max_length=10),
        ),
    ]
