# Generated by Django 4.2.21 on 2026-04-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Prescription', 'Prescription'), ('Sick Note', 'Sick Note'), ('Referral Letter', 'Referral Letter')], max_length=20)),
                ('content', models.TextField()),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('issued_by', models.CharField(default='Dr. Sarah Malan', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
