# Generated by Django 4.2.21 on 2026-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Clinical', 'Clinical Documents'), ('Administrative', 'Administrative Documents'), ('Compliance', 'Compliance & Legal Documents')], default='Clinical', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('Consultation Note', 'Consultation Note'), ('Patient Medical History', 'Patient Medical History'), ('Referral Letter', 'Referral Letter'), ('Lab Result', 'Lab Result'), ('Consent Form', 'Consent Form'), ('Prescription', 'Prescription'), ('Sick Note', 'Sick Note'), ('Patient Intake Form', 'Patient Intake Form'), ('Billing Statement', 'Billing Statement'), ('Practice Policy', 'Practice Policy'), ('Audit Log', 'Audit Log'), ('Record Retention Policy', 'Record Retention Policy'), ('Incident Report', 'Incident Report')], max_length=40),
        ),
    ]
