# Generated by Django 4.2.21 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_document_attachment_document_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('Consultation Note', 'Consultation Note'), ('Patient Medical History', 'Patient Medical History'), ('Referral Letter', 'Referral Letter'), ('Lab Request Form', 'Lab / Blood Test Request'), ('Radiology Request Form', 'Radiology Request (X-ray / Ultrasound)'), ('Lab Result', 'Lab Result'), ('Consent Form', 'Consent Form'), ('POPIA Consent', 'POPIA Consent Form'), ('Prescription', 'Prescription'), ('Sick Note', 'Sick / Medical Certificate'), ('Motivation Letter', 'Motivation Letter (Pre-authorisation)'), ('Claim Form', 'Medical Aid Claim Form'), ('Patient Intake Form', 'Patient Intake Form'), ('Vaccination Record', 'Vaccination Record'), ('Billing Statement', 'Billing Statement'), ('Practice Policy', 'Practice Policy'), ('Audit Log', 'Audit Log'), ('Record Retention Policy', 'Record Retention Policy'), ('Incident Report', 'Incident Report')], max_length=40),
        ),
    ]
