# Generated by Django 4.2.21 on 2026-04-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('subjective', models.TextField(verbose_name='Subjective (Symptoms)')),
                ('objective', models.TextField(verbose_name='Objective (Examination)')),
                ('assessment', models.TextField(verbose_name='Assessment (Diagnosis)')),
                ('plan', models.TextField(verbose_name='Plan (Treatment)')),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
