# Generated by Django 4.2.21 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True, verbose_name="Chief complaint (patient's own words)"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='differential_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Differential diagnosis'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD-10 code'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lab_requests',
            field=models.TextField(blank=True, help_text='One per line', null=True, verbose_name='Lab / blood test requests'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='radiology_requests',
            field=models.TextField(blank=True, help_text='One per line', null=True, verbose_name='Radiology requests (X-ray, ultrasound, etc.)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referral to (specialist / facility)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sick_note_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sick note (days)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sick_note_employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sick_note_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sick_note_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='assessment',
            field=models.TextField(verbose_name='A — Assessment (Diagnosis)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='objective',
            field=models.TextField(verbose_name='O — Objective (Examination findings)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(verbose_name='P — Plan (Treatment)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='subjective',
            field=models.TextField(verbose_name='S — Subjective (History of presenting illness)'),
        ),
    ]
