# Generated by Django 4.2.21 on 2026-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='bp_reading',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='BP (e.g. 120/80)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Assessment / Diagnosis'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for visit'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='O — Objective (Examination findings)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='plan',
            field=models.TextField(blank=True, null=True, verbose_name='P — Plan (Treatment)'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='subjective',
            field=models.TextField(blank=True, null=True, verbose_name='Clinical Notes'),
        ),
    ]
