# Generated by Django 4.2.21 on 2026-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_bp_reading_consultation_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='review',
            field=models.TextField(blank=True, help_text='Progress since last visit — current treatment response, adherence, concerns', null=True, verbose_name='Review'),
        ),
    ]
