# Generated by Django 4.2.21 on 2026-05-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='reviewed_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='consultations.consultation', verbose_name='Review of'),
        ),
    ]
