# Generated by Django 4.2.21 on 2026-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_reviewed_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionPrescriptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(db_index=True, max_length=200)),
                ('prescription', models.CharField(max_length=500)),
                ('count', models.IntegerField(default=1)),
                ('is_seeded', models.BooleanField(default=False)),
                ('last_seen', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
                'unique_together': {('condition', 'prescription')},
            },
        ),
    ]
