# Generated by Django 4.2.21 on 2026-06-02 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_alter_consultation_icd10_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('lab', 'Laboratory'), ('radiology', 'Radiology'), ('both', 'Both')], default='radiology', max_length=10)),
                ('practice_no', models.CharField(blank=True, max_length=50, verbose_name='Practice number')),
                ('email', models.EmailField(blank=True, help_text='Where the results link / report is sent', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lab', 'Laboratory'), ('radiology', 'Radiology')], max_length=10)),
                ('requested_items', models.TextField(blank=True, help_text='One exam/test per line', verbose_name='Requested items')),
                ('history', models.TextField(blank=True, verbose_name='Clinical history')),
                ('nappi_code', models.CharField(blank=True, max_length=50, verbose_name='Nappi code')),
                ('deliver_to', models.CharField(choices=[('rooms', 'Deliver to rooms'), ('ward', 'Hospital ward'), ('patient', 'Give to patient')], default='rooms', max_length=10)),
                ('provider_name', models.CharField(blank=True, help_text='Used if no saved provider is selected', max_length=200)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Awaiting results'), ('submitted', 'Submitted — awaiting review'), ('confirmed', 'Confirmed & filed'), ('declined', 'Declined')], default='sent', max_length=10)),
                ('result_text', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='investigation_results/%Y/%m/')),
                ('submitted_by', models.CharField(blank=True, max_length=200, verbose_name='Submitted by')),
                ('provider_note', models.TextField(blank=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('honeypot', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_requests', to='consultations.consultation')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consultations.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('consultation', 'kind')},
            },
        ),
    ]
