# Generated by Django 4.2.21 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authorization_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Auth. number (medical aid)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD-10 code'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referring_doctor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referring doctor'),
        ),
    ]
