# Generated by Django 4.2.21 on 2026-05-10 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_employer_patient_home_language_and_more'),
        ('appointments', '0004_appointment_status_checkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30)),
                ('reason_for_visit', models.TextField()),
                ('is_new_patient', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('popia_consent', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('medical_aid_name', models.CharField(blank=True, max_length=100)),
                ('medical_aid_number', models.CharField(blank=True, max_length=50)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('phase2_completed', models.BooleanField(default=False)),
                ('phase2_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('daily_token', models.CharField(max_length=64)),
                ('honeypot', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
