# Generated by Django 4.2.21 on 2026-05-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_reviewed_consultation'),
        ('appointments', '0005_checkinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Arrival'), ('queued', 'Added to Queue'), ('moved', 'Moved to Another Date'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='consultations.consultation')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('consultation', 'date')},
            },
        ),
    ]
