# Generated by Django 4.2.21 on 2026-05-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_pendingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreview',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_review', to='appointments.appointment'),
        ),
    ]
