# Generated by Django 4.2.21 on 2026-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_pendingreview_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Arrival'), ('self_arrived', 'Self Check-In Confirmed'), ('queued', 'Added to Queue'), ('moved', 'Moved to Another Date'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
