# Generated by Django 4.2.21 on 2026-05-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_pendingreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrequest',
            name='alcohol_use',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='current_medication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='employer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='medical_aid_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='smoking_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='title',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='checkinrequest',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Checked In', 'Checked In'), ('With Doctor', 'With Doctor'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Scheduled', max_length=20),
        ),
    ]
