# Generated by Django 4.2.21 on 2026-06-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_principal_member_id_and_more'),
        ('appointments', '0011_extend_checkinrequest_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('appointment_type', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid — awaiting review'), ('converted', 'Converted to appointment'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('payfast_payment_id', models.CharField(blank=True, max_length=100)),
                ('honeypot', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_booking', to='appointments.appointment')),
                ('matched_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_bookings', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
