# Generated by Django 4.2.21 on 2026-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_webbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbooking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested — awaiting confirmation'), ('pending_payment', 'Pending payment'), ('paid', 'Paid — awaiting review'), ('converted', 'Converted to appointment'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
