# Generated by Django 4.2.21 on 2026-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_webbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webbooking',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
