# Generated by Django 4.2.21 on 2026-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_webbooking_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webbooking',
            name='amount_cents',
        ),
        migrations.RemoveField(
            model_name='webbooking',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='webbooking',
            name='payfast_payment_id',
        ),
        migrations.AlterField(
            model_name='webbooking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested — awaiting confirmation'), ('converted', 'Converted to appointment'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
